//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaMVM.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ciudad
    {
        public int CiudadId { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> DepartamentoId { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual Departamento Departamento { get; set; }
    }
}
