//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaMVM.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comunicacion
    {
        public int ComunicacionId { get; set; }
        public Nullable<int> TipoCorrespondencia { get; set; }
        public string NumeroRadicado { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<int> ContactoDestinatario { get; set; }
        public Nullable<int> ContactoRemitente { get; set; }
        public Nullable<int> UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<bool> Eliminado { get; set; }
    
        public virtual Contacto Contacto { get; set; }
        public virtual Contacto Contacto1 { get; set; }
        public virtual Estado Estado1 { get; set; }
        public virtual TipoCorrespondencia TipoCorrespondencia1 { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
